flex/flex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('project.urls')),
]

flex/project/urls.py
from django.conf.urls import url

from .views import Home, MyProjectList, MyTaskList, hr_all, ProjectDashboard, BusinessPlan, new_relation, upd_relation, del_relation
from .views import TaskCreate, TaskUpdate, TaskDelete, UserCreate, UserUpdate, UserDelete


urlpatterns = [
    url(r'^$', Home.as_view(), name='home'),
    url(r'^adduser/$', UserCreate.as_view(), name='new_user'),
    url(r'^upduser/(?P<pk>\d+)/', UserUpdate.as_view(), name='upd_user'),
    url(r'^deluser/(?P<pk>\d+)$', UserDelete.as_view(), name='del_user'),
    url(r'^hr_all/$', hr_all, name='hr_all'),
    url(r'^mytasks/$', MyTaskList.as_view(), name='tasks'),
    url(r'^myprojects/$', MyProjectList.as_view(), name='projects'),
    url(r'^addtask/$', TaskCreate.as_view(), name='add_task'),
    url(r'^updtask/(?P<pk>\d+)/$', TaskUpdate.as_view(), name='upd_task'),
    url(r'^deltask/(?P<pk>\d+)/$', TaskDelete.as_view(), name='del_task'),
    url(r'^project_dashboard/(?P<pk>\d+)/$', ProjectDashboard.as_view(), name='project_dashboard'),
    url(r'^project_dashboard/(?P<pk>\d+)/budget/$', BusinessPlan.as_view(), name='business_plan'),
    url(r'^new_rel_task/(?P<pk>\d+)/$', new_relation, name='new_rel_task'),
    url(r'^upd_rel_task/(?P<pk>\d+)/$', upd_relation, name='upd_rel_task'),
    url(r'^del_rel_task/(?P<pk>\d+)/$', del_relation, name='del_rel_task')
]

flex/project/models.py
from django.db import models

# variables
STATUS = (
    (1, 'Не начато'),
    (2, 'В работе'),
    (3, 'Отстает'),
    (4, 'Выполнено'),
    (5, 'Приостановлено'))

ROLE = (
    (1, 'Участник'),
    (2, 'Менеджер'),
    (3, 'Стейкхолдер'),)

TASK_TYPE = (
    (1, 'Задача'),
    (2, 'Веха'))


class User(models.Model):
    """
    User model
    """
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    job = models.CharField(max_length=250)
    phone = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    project_role = models.SmallIntegerField(choices=ROLE, null=True, blank=True)
    occupation = models.CharField(max_length=250, null=True, blank=True)
    other = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Project(models.Model):
    """
    Project model
    """
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    start_date = models.DateField()
    duration = models.DurationField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    project_manager = models.ForeignKey(User, on_delete='PROTECT', null=True, blank=True)
    status = models.SmallIntegerField(choices=STATUS)

    def __str__(self):
        # return 'Project: {} | Project Manager: {} | Status: {}'.format(self.name, self.project_manager, self.status)
        return self.name

    def __unicode__(self):
        return self.name


def tasks_update(task_id, **kwargs):
    """
    Function for updating dates in tasks, if one task is changed.
    """
    if TaskRel.objects.filter(predecessors__id=task_id).exists():
        for next_task in TaskRel.objects.filter(predecessors__id=task_id).select_related('successor'):
            task_to_upd = next_task.successor
            if TaskRel.objects.filter(successor__id=task_to_upd.id).count() == 1:
                new_end = Task.objects.get(id=task_id).end_date
                task_to_upd.start_date = new_end
                task_to_upd.end_date = task_to_upd.start_date + task_to_upd.duration
                task_to_upd.save()
                tasks_update(task_to_upd.id)  # call function again for the next tasks
            # if task_to_upd has more, than one predecessor, define the latest finish date
            else:
                end_dates = dict()
                previous_tasks = TaskRel.objects.filter(successor__id=task_to_upd.id).select_related('predecessors')
                for each_task in previous_tasks:
                    end_dates[each_task.predecessors_id] = Task.objects.get(id=each_task.predecessors_id).end_date
                max_end_date = max(end_dates)
                task_to_upd.start_date = end_dates[max_end_date]
                task_to_upd.end_date = task_to_upd.start_date + task_to_upd.duration
                task_to_upd.save()
                tasks_update(task_to_upd.id)  # call function again for the next tasks


class Task(models.Model):
    """
    Task & milestone model
    """
    wbs_code = models.CharField(max_length=32, unique=True)
    task_type = models.SmallIntegerField(choices=TASK_TYPE, default=1)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    duration = models.DurationField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    responsible = models.ForeignKey(User, on_delete='SET_NULL', null=True, blank=True)
    status = models.SmallIntegerField(choices=STATUS)
    percent_complete = models.BigIntegerField(default=0)
    project = models.ForeignKey(Project, on_delete='SET_NULL', null=True, blank=True)
    optimistic_price = models.FloatField(null=True, blank=True)
    realistic_price = models.FloatField(null=True, blank=True)
    pessimistic_price = models.FloatField(null=True, blank=True)
    calculated_price = models.FloatField(null=True, blank=True)

    def __str__(self):
        return 'Task: {} | Responsible: {} | Status: {}'.format(self.name, self.responsible, self.status)

    def save(self, *args, **kwargs):
        """
        Redefine save method for model of Task, update dates in others successors
        """
        if not self.id:
            if self.start_date and self.duration:
                self.end_date = self.start_date + self.duration
            if self.pessimistic_price and self.realistic_price and self.optimistic_price:
                self.calculated_price = (self.optimistic_price + 4 * self.realistic_price + self.pessimistic_price) / 6
            super(Task, self).save()
            tasks_update(self.id)
        else:
            new_start = self.start_date
            new_duration = self.duration
            task_id = self.id
            self.end_date = new_start + new_duration
            old_start = Task.objects.get(id=task_id).start_date
            old_duration = Task.objects.get(id=task_id).duration
            if self.pessimistic_price and self.realistic_price and self.optimistic_price:
                self.calculated_price = (self.optimistic_price + 4 * self.realistic_price + self.pessimistic_price) / 6
            super(Task, self).save()
            if new_start != old_start or new_duration != old_duration:
                tasks_update(task_id)


class TaskRel(models.Model):
    """Relationships between models"""
    predecessors = models.ForeignKey(Task, on_delete='PROTECT', null=True, blank=True, unique=False)
    successor = models.ForeignKey(Task, on_delete='PROTECT', related_name='+', null=True, blank=True, unique=False)

    def save(self, *args, **kwargs):
        """
        Redefine save method for model of TaskRel, update dates, if new relation is created
        """
        task_id = self.predecessors_id
        super(TaskRel, self).save()
        return tasks_update(task_id)

    def delete(self, *args, **kwargs):
        """
        Redefine delete method for model of TaskRel, update dates, if new relation is deleted
        """
        if len(TaskRel.objects.filter(successor__id=self.successor_id)) > 1:
            current_task = self.successor
            super(TaskRel, self).delete()
            previous_tasks = TaskRel.objects.filter(successor__id=current_task.id)
            end_dates = dict()
            for each_task in previous_tasks:
                end_dates[each_task.predecessors_id] = Task.objects.get(id=each_task.predecessors_id).end_date
            task_w_max_end_date = int(max(end_dates))
            tasks_update(task_w_max_end_date)
        else:
            super(TaskRel, self).delete()

flex/project/views.py
from .models import Project, Task, User, TaskRel
from .forms import UserForm, TaskRelation, TaskForm
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from requests import request
from django.shortcuts import redirect
from django.db.models import Sum
from django.contrib import messages
import json


class Home(TemplateView):
    """
    Displaying active projects and tasks on home page
    """
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
            context = super(Home, self).get_context_data(**kwargs)
            context.update({
                'tasks': Task.objects.filter(status=2),
                'projects': Project.objects.filter(status=2),
            })
            return context


class MyTaskList(TemplateView):
    """
    Displaying task list on task list page
    """
    template_name = 'task_list.html'

    def get_context_data(self, **kwargs):
            context = super(MyTaskList, self).get_context_data(**kwargs)
            context.update({
                'tasks': Task.objects.all(),
                'tasksrel': TaskRel.objects.all(),
            })
            return context


class MyProjectList(ListView):
    """
    Displaying project list on project list page
    """
    template_name = 'project_list.html'
    model = Project

    def get_queryset(self):
        return Project.objects.all()


class TaskCreate(CreateView):
    """
    Display form for creating new task
    """
    form_class = TaskForm
    template_name = 'create_task.html'
    success_url = '/mytasks/'


class TaskUpdate(UpdateView):
    """
    Display form for update task
    """
    form_class = TaskForm
    template_name = 'create_task.html'
    success_url = '/mytasks/'
    queryset = Task.objects.all()


class TaskDelete(DeleteView):
    """
    Display form for removing task
    """
    model = Task
    template_name = 'delete_task.html'
    success_url = '/mytasks/'


def hr_all(request):
    """
    Show list of project team
    """
    users = User.objects.all()
    return render(request, 'hr_all.html', {'users': users})


def json_to_gantt():
    """
    Convert tasks data to json output
    """
    output = list()
    i = 0
    for each_task in Task.objects.all():
        task_info = list()
        task_info.append(str(Task.objects.get(id=each_task.id).id))
        task_info.append(Task.objects.get(id=each_task.id).name)
        js_start_date = (
            Task.objects.get(id=each_task.id).start_date.year,
            Task.objects.get(id=each_task.id).start_date.month,
            Task.objects.get(id=each_task.id).start_date.day
        )
        task_info.append(js_start_date)
        js_end_date = (
            Task.objects.get(id=each_task.id).end_date.year,
            Task.objects.get(id=each_task.id).end_date.month,
            Task.objects.get(id=each_task.id).end_date.day
        )
        task_info.append(js_end_date)
        task_info.append(Task.objects.get(id=each_task.id).duration.days)
        task_info.append(Task.objects.get(id=each_task.id).percent_complete)
        js_predecessors = list()
        if TaskRel.objects.filter(successor__id=each_task.id).exists():
            for item in TaskRel.objects.filter(successor__id=each_task.id):
                js_predecessors.append(str(item.predecessors_id))

            task_info.append(','.join(js_predecessors))
        else:
            task_info.append('')
        output.append(task_info)
        i += 1
    response = json.dumps(output)
    return response


class ProjectDashboard(TemplateView):
    """
    Display project dashboard
    """
    template_name = 'project_dashboard.html'

    def get_context_data(self, pk, **kwargs):
        context = super(ProjectDashboard, self).get_context_data(**kwargs)
        context.update({
            'tasks': Task.objects.filter(project_id=pk),
            'project': Project.objects.filter(pk=pk),
            'tasksrel': TaskRel.objects.all(),
            'output': json_to_gantt(),
        })
        return context


class BusinessPlan(TemplateView):
    template_name = 'business_plan.html'

    def get_context_data(self, pk, **kwargs):
        context = super(BusinessPlan, self).get_context_data(**kwargs)
        context.update({
            'tasks': Task.objects.filter(project_id=pk),
        })
        context['opt_price'] = Task.objects.all().aggregate(Sum('optimistic_price'))
        context['pess_price'] = Task.objects.all().aggregate(Sum('pessimistic_price'))
        context['real_price'] = Task.objects.all().aggregate(Sum('realistic_price'))
        context['calc_price'] = Task.objects.all().aggregate(Sum('calculated_price'))
        return context


def new_relation(request, pk):
    """
    Display form for creation of new relation between tasks with validation
    """
    form = TaskRelation()
    error_message = ''
    if request.method == 'POST':
        if pk != request.POST['predecessors']:
            task, created = TaskRel.objects.get_or_create(successor_id=pk, predecessors_id=request.POST['predecessors'])
            if not created:
                error_message = ('Такая связь уже существует',)
            else:
                return redirect('/mytasks')
        else:
            error_message = ('Нельзя связывать задачу с самой собой', )
    return render(request, 'create_rel.html', {'form': form, 'messages': error_message})


def upd_relation(request, pk):
    """
    Display form for editing relation between tasks with validation
    """
    form = TaskRelation()
    rel = TaskRel.objects.get(pk=pk)
    error_message = ''
    if request.method == 'POST':
        if int(rel.successor_id) == int(request.POST['predecessors']):
            error_message = ('Нельзя связывать задачу с самой собой', )
        elif TaskRel.objects.filter(
                predecessors_id=request.POST['predecessors'], successor_id=rel.successor_id).exists():
            error_message = ('Такая связь уже существует', )
        else:
            rel.predecessors_id = request.POST['predecessors']
            rel.save()
            return redirect('/mytasks')
    form = TaskRelation(initial={'predecessors': rel.predecessors})
    return render(request, 'edit_rel.html', {'form': form, 'rel': pk, 'messages': error_message})


def del_relation(request, pk):
    """
    Display form for removing task
    """
    form = None
    rel = TaskRel.objects.get(pk=pk)
    if request.method == 'POST':
        rel.delete()
        return redirect('/mytasks')
    else:
        return render(request, 'delete_rel.html', {'form': form, 'rel': rel})


class UserCreate(CreateView):
    """
    Create new user
    """
    form_class = UserForm
    template_name ='create_user.html'
    success_url = '/hr_all/'


class UserUpdate(UpdateView):
    """
    Edit users info
    """
    form_class = UserForm
    template_name ='create_user.html'
    success_url = '/hr_all/'
    queryset = User.objects.all()


class UserDelete(DeleteView):
    """
    Display form for removing user
    """
    model = User
    template_name = 'delete_user.html'
    success_url = '/hr_all/'

flex/project/templates/business_plan.html
{% extends 'index.html' %}

{% block project_budget %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h1">{{ project.first.name }}</h1>
    </div>

    <div class="container-fluid">
        <div class="row">
            <a href="#" class="card-link">Устав проекта</a>
            <a href="#" class="card-link">Объем работ</a>
            <a href="#" class="card-link">Команда проекта</a>
            <a href="#" class="card-link">Сетевая диаграмма</a>
            <a href="#" class="card-link">Диаграмма Ганта</a>
            <a href="#" class="card-link">Оценка времени</a>
            <a href="#" class="card-link">Бюджет</a>
            <a href="#" class="card-link">Оценка качества, стандартов и процессов</a>
            <a href="#" class="card-link">RASI матрица</a>
            <a href="#" class="card-link">Риск-анализ</a>
            <a href="#" class="card-link">Оценка закупок</a>
            <a href="#" class="card-link">План коммуникаций</a>
            <a href="#" class="card-link">Контроль изменений</a>
        </div>
    </div>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h2 class="h2">Задачи</h2>
    </div>


    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">WBS Код</th>
                <th scope="col">Тип</th>
                <th scope="col">Задача</th>
                <th scope="col">Исполнитель</th>
                <th scope="col">Статус</th>
                <th scope="col">Оптимистичный план</th>
                <th scope="col">Реалистичный план</th>
                <th scope="col">Пессиммистичный план</th>
                <th scope="col">PERT-оценка</th>
            </tr>
        </thead>

             <tbody>
                {% for task in tasks %}
                    <tr>
                        <th scope="row">{{ task.wbs_code }}</th>
                        <td>{{ task.get_task_type_display }}</td>
                        <td>{{ task.name }}</td>
                        <td>{{ task.responsible }}</td>
                        <td>{{ task.get_status_display }}</td>
                        <td>{{ task.optimistic_price|floatformat:-2 }}</td>
                        <td>{{ task.realistic_price|floatformat:-2 }}</td>
                        <td>{{ task.pessimistic_price|floatformat:-2 }}</td>
                        <td>{{ task.calculated_price|floatformat:-2 }}</td>
                    </tr>
                {% endfor %}
                    <tr>
                        <th scope="row"></th>
                        <td><b>Итого:</b></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>{{ opt_price.optimistic_price__sum|floatformat:-2 }}</td>
                        <td>{{ real_price.realistic_price__sum|floatformat:-2 }}</td>
                        <td>{{ pess_price.pessimistic_price__sum|floatformat:-2 }}</td>
                        <td>{{ calc_price.calculated_price__sum|floatformat:-2}}</td>
                    </tr>
            </tbody>
    </table>

{% endblock %}

flex/project/templates/delete_rel.html
{% extends 'index.html' %}

{% block delete_task %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Удалить связь {{ rel.successor.name }} <-- {{ rel.predecessors.name }}?</h4>
        <p>Проверьте необходимость удаления связи.</p>
        <hr>
        <p>Это действие нельзя отменить или восстановить связь обратно.</p>

        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="/mytasks/">
                <button type="button" class="btn btn-primary">Отмена</button>
            </a>
        </form>
    </div>
{% endblock %}

flex/project/templates/home.html
{% extends 'index.html' %}

{% block home %}

  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Активные проекты</h1>
  </div>

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Проект</th>
                <th scope="col">Старт</th>
                <th scope="col">Финиш</th>
                <th scope="col">Руководитель</th>
                <th scope="col">Статус</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
                <tr>
                    <td>{{ project.name }}</td>
                    <td>{{ project.start_date }}</td>
                    <td>{{ project.end_date }}</td>
                    <td>{{ project.project_manager }}</td>
                    <td>{{ project.get_status_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

        <br style="margin-bottom:3cm;"> </br>

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Активные задачи</h1>
      </div>

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">WBS Код</th>
                <th scope="col">Тип</th>
                <th scope="col">Задача</th>
                <th scope="col">Старт</th>
                <th scope="col">Финиш</th>
                <th scope="col">Исполнитель</th>
                <th scope="col">Статус</th>
                <th scope="col">Проект</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
                <tr>
                    <th scope="row">{{ task.wbs_code }}</th>
                    <td>{{ task.get_task_type_display }}</td>
                    <td>{{ task.name }}</td>
                    <td>{{ task.start_date }}</td>
                    <td>{{ task.end_date }}</td>
                    <td>{{ task.responsible }}</td>
                    <td>{{ task.get_status_display }}</td>
                    <td>{{ task.project }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

flex/project/templates/hr_all.html
{% extends 'index.html' %}

{% block hr_all %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Участники</h1>
        <a href="/adduser/">
            <button type="button" class="btn btn-primary">Добавить участника</button>
        </a>
        </div>

    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Должность</th>
                <th scope="col">Телефон</th>
                <th scope="col">Почта</th>
                <th scope="col">Роль в проекте</th>
                <th scope="col">Занятость</th>
                <th scope="col">Проект</th>
                <th scope="col">Другое</th>

            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>


                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.first_name }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.last_name }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.job }}
                        </a>
                        </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.phone }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.email }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.get_project_role_display }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.occupation }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.project }}
                        </a>
                    </td>
                    <td>
                        <a href="/upduser/{{ user.pk }}/" class="card-link">
                            {{ user.other }}
                        </a>
                    </td>

                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

flex/project/templates/project_dashboard.html
{% extends 'index.html' %}

{% block project_dashboard %}


  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);

    function daysToMilliseconds(days) {
      return days * 24 * 60 * 60 * 1000;
    }

    function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Task ID');
      data.addColumn('string', 'Task Name');
      data.addColumn('date', 'Start Date');
      data.addColumn('date', 'End Date');
      data.addColumn('number', 'Duration');
      data.addColumn('number', 'Percent Complete');
      data.addColumn('string', 'Dependencies');

      var rows = {{ output|safe }};
      var tasks = new Array
        for (i=0; i< rows.length; i++) {
            var arr = [rows[i][0],
                rows[i][1],
                new Date(rows[i][2]),
                new Date(rows[i][3]),
                daysToMilliseconds(rows[i][4]),
                rows[i][5],
                rows[i][6]];
            tasks.push(arr);
        };
        data.addRows(tasks);

      var options = {
        height: 275
      };

      var chart = new google.visualization.Gantt(document.getElementById('chart_div'));

      chart.draw(data, options);
    }
  </script>


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h1">{{ project.first.name }}</h1>
    </div>

    <div class="container-fluid">
        <div class="row">
            <a href="#" class="card-link">Устав проекта</a>
            <a href="#" class="card-link">Объем работ</a>
            <a href="#" class="card-link">Команда проекта</a>
            <a href="#" class="card-link">Сетевая диаграмма</a>
            <a href="#" class="card-link">Оценка времени</a>
            <a href="budget" class="card-link">Бюджет</a>
            <a href="#" class="card-link">Оценка качества, стандартов и процессов</a>
            <a href="#" class="card-link">RASI матрица</a>
            <a href="#" class="card-link">Риск-анализ</a>
            <a href="#" class="card-link">Оценка закупок</a>
            <a href="#" class="card-link">План коммуникаций</a>
            <a href="#" class="card-link">Контроль изменений</a>
        </div>
    </div>

    <br style="margin-bottom:3cm;"> </br>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h2 class="h2">Диаграмма Гантта</h2>
    </div>
    <div id="chart_div"></div>

    <br style="margin-bottom:3cm;"> </br>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h2 class="h2">Задачи</h2>
    </div>


    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">WBS Код</th>
                <th scope="col">Тип</th>
                <th scope="col">Задача</th>
                <th scope="col">Старт</th>
                <th scope="col">Финиш</th>
                <th scope="col">Исполнитель</th>
                <th scope="col">Статус</th>
                <th scope="col">Предыдущая задача</th>
                <th scope="col">Проект</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
                <tr>
                    <th scope="row">{{ task.wbs_code }}</th>
                    <td>{{ task.get_task_type_display }}</td>
                    <td>{{ task.name }}</td>
                    <td>{{ task.start_date }}</td>
                    <td>{{ task.end_date }}</td>
                    <td>{{ task.responsible }}</td>
                    <td>{{ task.get_status_display }}</td>
                    <td>
                        {% for rel in tasksrel %}
                            {% if rel.successor.id == task.id %}
                                {{ rel.predecessors.name }}<br>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ task.project }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

flex/project/templates/task_list.html
{% extends 'index.html' %}

{% block tasks %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Задачи</h1>
        <a href="/addtask/">
        <button type="button" class="btn btn-primary">Добавить задачу</button>
        </a>
    </div>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">WBS Код</th>
                <th scope="col">Тип</th>
                <th scope="col">Задача</th>
                <th scope="col">Старт</th>
                <th scope="col">Финиш</th>
                <th scope="col">Исполнитель</th>
                <th scope="col">Статус</th>
                <th scope="col">Предыдущая задача</th>
                <th scope="col">Проект</th>
            </tr>
        </thead>
        <tbody>

            {% for task in tasks %}
                <tr>
{#                    <th scope="row">#}
                        <td>
                            <a href="/updtask/{{ task.pk }}/" class="card-link">
                                {{ task.wbs_code }}
                            </a>
                        </td>
                        <td>
                            <a href="/updtask/{{ task.pk }}/" class="card-link">
                                {{ task.get_task_type_display }}
                            </a>
                        </td>
                        <td>
                            <a href="/updtask/{{ task.pk }}/" class="card-link">
                                {{ task.name }}
                            </a>
                        </td>
                        <td>{{ task.start_date }}</td>
                        <td>{{ task.end_date }}</td>
                        <td>{{ task.responsible }}</td>
                        <td>{{ task.get_status_display }}</td>
                        <td>

                                {% for rel in tasksrel %}
                                    {% if rel.successor.id == task.id %}
                                        <a href="/upd_rel_task/{{ rel.pk }}/" class="card-link">
                                            {{ rel.predecessors.name }}<br>
                                        </a>
                                    {% endif %}
                                {% endfor %}

                            <a href="/new_rel_task/{{ task.pk }}/" class="card-link">
                                <p>Добавить связь</p>
                            </a>

                        </td>
                        <td>{{ task.project }}</td>

                    </a>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}